name: Temp

on:
  push:
    branches:
      - temp

jobs:
  wip:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.27.1

      - name: Build
        run: pnpm -r --parallel --filter "./packages/* build"
